# fly.toml file generated for triviabuzzer on 2022-12-05T17:09:46-06:00

app = "triviabuzzer"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[mounts]
  source = "trivia_buzzer_data"
  destination = "/data"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "triviabuzzer.fly.dev"
  PORT = "8080"
  PHX_SERVER = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
